-- ============================================================
-- Yayoo Femme - Seed Data
-- ============================================================

-- EBOOKS
insert into ebooks (title, slug, description, price, is_free, is_premium, category)
values
  ('Le Guide Ultime du Style Capsule', 'guide-style-capsule', 'Construisez une garde-robe intemporelle avec seulement 30 pièces essentielles.', 0, true, false, 'style'),
  ('Skincare Naturelle : Les 10 Actifs Essentiels', 'skincare-naturelle-actifs', 'Décryptez les ingrédients clés pour une peau éclatante au naturel.', 9.99, false, false, 'beauty'),
  ('Parfums : Trouver Sa Signature Olfactive', 'parfums-signature-olfactive', 'Guide complet pour choisir un parfum qui vous ressemble vraiment.', 9.99, false, false, 'perfume'),
  ('La Bible des Cadeaux Féminins', 'bible-cadeaux-feminins', 'Plus de 100 idées cadeaux pour toutes les occasions et tous les budgets.', 14.99, false, false, 'gifts'),
  ('Mode Éthique & Durable : Par Où Commencer ?', 'mode-ethique-durable', 'Conseils pratiques pour adopter une consommation de mode plus responsable.', 0, true, false, 'style'),
  ('Maquillage Naturel : Techniques Pro', 'maquillage-naturel-techniques', 'Maîtrisez les techniques de maquillage nude et naturel comme une experte.', 12.99, false, true, 'beauty'),
  ('Tendances Mode 2025 : Le Décryptage', 'tendances-mode-2025', 'Analyse complète des tendances qui vont dominer la saison.', 7.99, false, false, 'style');

-- PRODUCTS (100 items across categories)
insert into products (name, brand, category, subcategory, description, price, image_url, product_url, affiliate_url, seller, commission_rate, material, sizes, colors, target_styles, target_occasions, target_profiles, quality_score, safety_score, value_score, trend_score, commission_score, stock_status)
values
  -- STYLE - Tops
  ('Blouse en soie fluide', 'Sézane', 'style', 'tops', 'Blouse légère en soie avec col romantique, parfaite pour le bureau ou une soirée.', 95.00, null, '#', '#', 'Sézane', 0.06, 'Soie 100%', ARRAY['XS','S','M','L','XL'], ARRAY['ivoire','rose poudré','noir'], ARRAY['romantique','chic','bohème'], ARRAY['bureau','soirée','week-end'], ARRAY['25-35','35-45'], 88, 82, 78, 85, 60, 'in_stock'),
  ('T-shirt en coton biologique', 'Arket', 'style', 'tops', 'T-shirt basique en coton bio certifié GOTS, coupe droite décontractée.', 35.00, null, '#', '#', 'Arket', 0.05, 'Coton bio', ARRAY['XS','S','M','L','XL','XXL'], ARRAY['blanc','noir','gris','beige'], ARRAY['casual','minimaliste'], ARRAY['quotidien','week-end'], ARRAY['18-25','25-35','35-45'], 85, 90, 88, 72, 50, 'in_stock'),
  ('Col roulé en cachemire', 'Uniqlo', 'style', 'tops', 'Col roulé ultra-doux en cachemire pur, chaud et élégant.', 79.90, null, '#', '#', 'Uniqlo', 0.04, 'Cachemire 100%', ARRAY['XS','S','M','L','XL'], ARRAY['camel','gris chiné','marine','bordeaux'], ARRAY['chic','minimaliste','classique'], ARRAY['bureau','quotidien'], ARRAY['25-35','35-45','45+'], 92, 85, 82, 80, 40, 'in_stock'),
  ('Crop top à volants', 'Mango', 'style', 'tops', 'Crop top festif avec volants asymétriques, idéal pour les soirées estivales.', 29.99, null, '#', '#', 'Mango', 0.07, 'Polyester', ARRAY['XS','S','M','L'], ARRAY['blanc','fuchsia','citron'], ARRAY['festif','tendance','sexy'], ARRAY['soirée','plage'], ARRAY['18-25','25-35'], 72, 70, 75, 90, 70, 'in_stock'),
  ('Chemise en lin oversize', 'H&M', 'style', 'tops', 'Chemise ample en lin lavé, à la fois décontractée et chic.', 24.99, null, '#', '#', 'H&M', 0.06, 'Lin 100%', ARRAY['XS','S','M','L','XL','XXL'], ARRAY['blanc','sable','vert sauge'], ARRAY['bohème','casual','minimaliste'], ARRAY['week-end','plage','quotidien'], ARRAY['18-25','25-35','35-45'], 80, 82, 85, 78, 60, 'in_stock'),

  -- STYLE - Bottoms
  ('Jean taille haute Straight', 'Levi''s', 'style', 'bottoms', 'Jean 501 iconique en denim rigide, coupe droite vintage.', 119.00, null, '#', '#', 'Levi''s', 0.05, 'Denim coton', ARRAY['24','25','26','27','28','29','30','31','32'], ARRAY['indigo','noir','blanc'], ARRAY['casual','rock','vintage'], ARRAY['quotidien','week-end'], ARRAY['18-25','25-35','35-45'], 90, 85, 80, 88, 50, 'in_stock'),
  ('Jupe midi plissée', 'Zara', 'style', 'bottoms', 'Jupe midi plissée en satin, mouvement élégant pour toutes occasions.', 39.95, null, '#', '#', 'Zara', 0.08, 'Polyester satiné', ARRAY['XS','S','M','L','XL'], ARRAY['mauve','chocolat','vert émeraude'], ARRAY['chic','romantique'], ARRAY['bureau','soirée'], ARRAY['18-25','25-35','35-45'], 78, 72, 80, 92, 80, 'in_stock'),
  ('Legging sport taille haute', 'Lululemon', 'style', 'bottoms', 'Legging compression avec poche latérale, tissu respirant 4-way stretch.', 118.00, null, '#', '#', 'Lululemon', 0.05, 'Nylon/Lycra', ARRAY['XS','S','M','L','XL'], ARRAY['noir','gris','bordeaux'], ARRAY['sport','athleisure'], ARRAY['sport','quotidien'], ARRAY['18-25','25-35','35-45'], 95, 88, 75, 85, 50, 'in_stock'),
  ('Pantalon cigarette', 'Ba&sh', 'style', 'bottoms', 'Pantalon taille haute coupe cigarette, allonge la silhouette.', 195.00, null, '#', '#', 'Ba&sh', 0.06, 'Crêpe polyester', ARRAY['34','36','38','40','42'], ARRAY['noir','crème','kaki'], ARRAY['chic','classique'], ARRAY['bureau','soirée'], ARRAY['25-35','35-45'], 88, 80, 72, 82, 60, 'in_stock'),
  ('Short en velours côtelé', '& Other Stories', 'style', 'bottoms', 'Short à taille haute en velours côtelé fin, look 70s chic.', 45.00, null, '#', '#', '& Other Stories', 0.07, 'Coton velours', ARRAY['XS','S','M','L'], ARRAY['camel','olive','bordeaux'], ARRAY['vintage','casual','bohème'], ARRAY['week-end','soirée'], ARRAY['18-25','25-35'], 82, 80, 78, 85, 70, 'in_stock'),

  -- STYLE - Dresses
  ('Robe portefeuille en viscose', 'Sézane', 'style', 'dresses', 'Robe portefeuille intemporelle en viscose fluide, imprimé fleuri délicat.', 145.00, null, '#', '#', 'Sézane', 0.06, 'Viscose 100%', ARRAY['XS','S','M','L','XL'], ARRAY['fleuri rose','fleuri bleu'], ARRAY['romantique','chic'], ARRAY['soirée','bureau','week-end'], ARRAY['25-35','35-45'], 89, 82, 76, 87, 60, 'in_stock'),
  ('Robe midi en dentelle', 'Anthropologie', 'style', 'dresses', 'Robe midi en dentelle élaborée, doublure contrastante, fermeture dos.', 185.00, null, '#', '#', 'Anthropologie', 0.07, 'Dentelle polyester', ARRAY['XS','S','M','L'], ARRAY['ivoire','noir'], ARRAY['romantique','bohème','soirée'], ARRAY['soirée','mariage'], ARRAY['25-35','35-45'], 85, 78, 70, 88, 70, 'in_stock'),
  ('Combinaison pantalon large', 'Mango', 'style', 'dresses', 'Combinaison large avec ceinture à nouer, look estival sophistiqué.', 69.99, null, '#', '#', 'Mango', 0.07, 'Lin mélangé', ARRAY['XS','S','M','L','XL'], ARRAY['blanc','terracotta','marine'], ARRAY['chic','tendance'], ARRAY['soirée','plage'], ARRAY['18-25','25-35'], 80, 76, 78, 90, 70, 'in_stock'),
  ('Robe courte à smocks', 'Free People', 'style', 'dresses', 'Robe courte en coton avec fronces smocquées et bretelles réglables.', 98.00, null, '#', '#', 'Free People', 0.06, 'Coton', ARRAY['XS','S','M','L'], ARRAY['pêche','lavande','écru'], ARRAY['bohème','festif'], ARRAY['festival','plage','week-end'], ARRAY['18-25','25-35'], 83, 80, 76, 88, 60, 'in_stock'),
  ('Robe chemise oversize en soie', 'Jacquemus', 'style', 'dresses', 'Robe chemise oversize en soie légère, col classique, manches longues.', 350.00, null, '#', '#', 'Jacquemus', 0.05, 'Soie', ARRAY['XS','S','M','L'], ARRAY['ivoire','ciel','abricot'], ARRAY['chic','minimaliste','luxe'], ARRAY['soirée','bureau'], ARRAY['25-35','35-45'], 95, 88, 65, 92, 50, 'in_stock'),

  -- STYLE - Outerwear
  ('Manteau laine double face', 'Max Mara', 'style', 'outerwear', 'Manteau iconique en laine double face, coupe droite élégante.', 1590.00, null, '#', '#', 'Max Mara', 0.04, 'Laine/cachemire', ARRAY['36','38','40','42','44'], ARRAY['camel','blanc cassé','noir'], ARRAY['luxe','classique','chic'], ARRAY['bureau','soirée','quotidien'], ARRAY['35-45','45+'], 98, 92, 60, 90, 40, 'in_stock'),
  ('Veste en jean brut', 'Levi''s', 'style', 'outerwear', 'Veste trucker en denim 100% coton, classique indestructible.', 110.00, null, '#', '#', 'Levi''s', 0.05, 'Denim coton', ARRAY['XS','S','M','L','XL','XXL'], ARRAY['bleu brut','noir','medium'], ARRAY['casual','rock','vintage'], ARRAY['quotidien','week-end'], ARRAY['18-25','25-35','35-45'], 88, 85, 82, 85, 50, 'in_stock'),
  ('Blazer croisé en laine', 'Cos', 'style', 'outerwear', 'Blazer croisé structuré en laine recyclée, coupe ajustée.', 220.00, null, '#', '#', 'Cos', 0.05, 'Laine recyclée', ARRAY['XS','S','M','L','XL'], ARRAY['noir','beige','anthracite'], ARRAY['minimaliste','chic','classique'], ARRAY['bureau','soirée'], ARRAY['25-35','35-45'], 90, 88, 78, 85, 50, 'in_stock'),
  ('Imperméable trench beige', 'Burberry', 'style', 'outerwear', 'Trench-coat iconique en gabardine de coton, col boutonnant.', 1990.00, null, '#', '#', 'Burberry', 0.04, 'Coton gabardine', ARRAY['6','8','10','12','14'], ARRAY['beige','noir','marine'], ARRAY['classique','luxe','chic'], ARRAY['bureau','quotidien'], ARRAY['35-45','45+'], 98, 90, 58, 88, 40, 'in_stock'),
  ('Parka matelassée légère', 'Patagonia', 'style', 'outerwear', 'Parka légère en duvet recyclé, imperméable, poches pratiques.', 329.00, null, '#', '#', 'Patagonia', 0.05, 'Recyclé/duvet', ARRAY['XS','S','M','L','XL'], ARRAY['rouge framboise','vert forêt','noir'], ARRAY['casual','outdoor','tendance'], ARRAY['quotidien','outdoor'], ARRAY['18-25','25-35','35-45'], 92, 88, 75, 82, 50, 'in_stock'),

  -- BEAUTY - Skincare
  ('Sérum Vitamine C 20%', 'The Ordinary', 'beauty', 'skincare', 'Sérum concentré en vitamine C pure pour un éclat immédiat et une protection antioxydante.', 12.00, null, '#', '#', 'Sephora', 0.08, null, null, null, ARRAY['minimaliste','naturel'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45'], 88, 90, 95, 85, 80, 'in_stock'),
  ('Crème hydratante SPF50', 'La Roche-Posay', 'beauty', 'skincare', 'Crème légère protection solaire SPF50 avec acide hyaluronique, texte non grasse.', 24.90, null, '#', '#', 'Pharmacie en ligne', 0.07, null, null, null, ARRAY['naturel','soin'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45','45+'], 92, 95, 88, 80, 70, 'in_stock'),
  ('Huile de nuit à l''argan', 'L''Occitane', 'beauty', 'skincare', 'Huile sèche visage à l''huile d''argan pure, régénère et nourrit pendant la nuit.', 55.00, null, '#', '#', 'L''Occitane', 0.06, null, null, null, ARRAY['naturel','luxe'], ARRAY['quotidien'], ARRAY['25-35','35-45','45+'], 85, 92, 78, 82, 60, 'in_stock'),
  ('Gommage sucre lèvres', 'Lush', 'beauty', 'skincare', 'Gommage exfoliant doux pour les lèvres à base de sucre et d''huiles végétales.', 10.95, null, '#', '#', 'Lush', 0.08, null, null, null, ARRAY['naturel','soin'], ARRAY['quotidien'], ARRAY['18-25','25-35'], 80, 88, 90, 75, 80, 'in_stock'),
  ('Masque hydratant tissu', 'Garnier', 'beauty', 'skincare', 'Masque en tissu bio saturé en sérum hydratant à l''aloe vera.', 3.49, null, '#', '#', 'Pharmacie en ligne', 0.09, null, null, null, ARRAY['soin'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45'], 78, 85, 95, 70, 90, 'in_stock'),
  ('Contour des yeux anti-âge', 'Clarins', 'beauty', 'skincare', 'Soin spécifique contour des yeux pour réduire poches et cernes.', 62.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['luxe','soin'], ARRAY['quotidien'], ARRAY['35-45','45+'], 90, 88, 72, 80, 70, 'in_stock'),
  ('Crème BB teintée naturelle', 'NARS', 'beauty', 'skincare', 'BB Crème légère SPF30, 8 teintes, hydratation et couverture naturelle.', 38.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['maquillage','naturel'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45'], 88, 85, 80, 85, 70, 'in_stock'),

  -- BEAUTY - Makeup
  ('Fond de teint longue tenue', 'Charlotte Tilbury', 'beauty', 'makeup', 'Foundation légère 24h, 40 teintes, fini naturel satné.', 45.00, null, '#', '#', 'Charlotte Tilbury', 0.07, null, null, null, ARRAY['maquillage','chic'], ARRAY['bureau','soirée'], ARRAY['18-25','25-35','35-45'], 92, 85, 75, 90, 70, 'in_stock'),
  ('Palette fards à paupières', 'Urban Decay', 'beauty', 'makeup', 'Palette Naked de 12 teintes neutres et fumées, ultra-pigmentées.', 54.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['maquillage'], ARRAY['soirée','bureau'], ARRAY['18-25','25-35','35-45'], 95, 82, 78, 88, 70, 'in_stock'),
  ('Rouge à lèvres satiné', 'MAC', 'beauty', 'makeup', 'Rouge à lèvres semi-mat à la formule crémeuse, plus de 200 teintes.', 23.00, null, '#', '#', 'MAC', 0.06, null, null, null, ARRAY['maquillage','chic'], ARRAY['quotidien','soirée'], ARRAY['18-25','25-35','35-45','45+'], 90, 82, 82, 85, 60, 'in_stock'),
  ('Mascara volume extrême', 'Lancôme', 'beauty', 'makeup', 'Mascara Hypnôse Volume-à-Porter pour un volume spectaculaire sans alourdissement.', 32.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['maquillage'], ARRAY['quotidien','bureau','soirée'], ARRAY['18-25','25-35','35-45','45+'], 92, 80, 80, 88, 70, 'in_stock'),
  ('Blush liquide buildable', 'Milk Makeup', 'beauty', 'makeup', 'Blush liquide ultra-pigmenté pour un flush naturel ou intense.', 28.00, null, '#', '#', 'Sephora', 0.08, null, null, null, ARRAY['maquillage','tendance'], ARRAY['quotidien'], ARRAY['18-25','25-35'], 88, 82, 82, 92, 80, 'in_stock'),
  ('Correcteur anti-cernes', 'Nars', 'beauty', 'makeup', 'Correcteur crémeux longue tenue qui efface les cernes sans s''incruster.', 34.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['maquillage'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45','45+'], 92, 82, 78, 85, 70, 'in_stock'),

  -- BEAUTY - Haircare
  ('Masque protéiné cheveux', 'Kérastase', 'beauty', 'haircare', 'Masque Résistance renforçant pour cheveux abîmés et fragilisés.', 48.00, null, '#', '#', 'Kérastase', 0.07, null, null, null, ARRAY['soin'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45','45+'], 95, 88, 75, 85, 70, 'in_stock'),
  ('Huile d''argan cheveux', 'Moroccanoil', 'beauty', 'haircare', 'Huile de soin multi-usages pour brillance, douceur et protection thermique.', 46.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['soin','naturel'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45','45+'], 95, 88, 76, 88, 70, 'in_stock'),
  ('Shampoing sans sulfates', 'Davines', 'beauty', 'haircare', 'Shampoing doux pour cuir chevelu sensible, formule vegan certifiée.', 25.00, null, '#', '#', 'Davines', 0.07, null, null, null, ARRAY['naturel','soin'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45','45+'], 90, 92, 82, 80, 70, 'in_stock'),
  ('Spray thermo-protecteur', 'Redken', 'beauty', 'haircare', 'Spray protecteur chaleur jusqu''à 230°C avec protéines pour cheveux colorés.', 22.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['soin'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45'], 88, 85, 82, 80, 70, 'in_stock'),

  -- BEAUTY - Bodycare
  ('Lait corps nourrissant', 'Weleda', 'beauty', 'bodycare', 'Lait corporel nourrissant à l''amande douce, certifié NATRUE.', 16.90, null, '#', '#', 'Pharmacie en ligne', 0.07, null, null, null, ARRAY['naturel','soin'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45','45+'], 88, 95, 90, 78, 70, 'in_stock'),
  ('Gommage corps café', 'Frank Body', 'beauty', 'bodycare', 'Gommage corps exfoliant naturel à base de marc de café et huile de coco.', 19.99, null, '#', '#', 'Frank Body', 0.08, null, null, null, ARRAY['naturel'], ARRAY['quotidien'], ARRAY['18-25','25-35'], 85, 90, 88, 82, 80, 'in_stock'),
  ('Huile sèche corps', 'Nuxe', 'beauty', 'bodycare', 'Huile prodigieuse sèche corps multi-fonctions, 7 huiles végétales précieuses.', 29.90, null, '#', '#', 'Pharmacie en ligne', 0.07, null, null, null, ARRAY['naturel','luxe'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45','45+'], 90, 90, 85, 85, 70, 'in_stock'),

  -- PERFUME
  ('Eau de parfum florale - Miss Dior', 'Dior', 'perfume', 'floral', 'Fragrance féminine iconique avec cœur de rose et musc blanc, longue tenue.', 130.00, null, '#', '#', 'Sephora', 0.06, null, null, null, ARRAY['romantique','chic'], ARRAY['quotidien','soirée'], ARRAY['18-25','25-35','35-45'], 92, 85, 70, 90, 60, 'in_stock'),
  ('Parfum oriental boisé - Black Opium', 'Yves Saint Laurent', 'perfume', 'oriental', 'Notes de café noir et vanille pour une fragrance addictive et envoûtante.', 120.00, null, '#', '#', 'Sephora', 0.06, null, null, null, ARRAY['séductrice','mystérieuse'], ARRAY['soirée'], ARRAY['18-25','25-35'], 90, 83, 72, 88, 60, 'in_stock'),
  ('Cologne fraîche unisexe - CK One', 'Calvin Klein', 'perfume', 'fresh', 'Eau de toilette fraîche unisexe, notes agrumes et thé vert, légèreté garantie.', 65.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['minimaliste','casual'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45'], 85, 83, 82, 78, 70, 'in_stock'),
  ('Parfum ambre vanillé - La Vie est Belle', 'Lancôme', 'perfume', 'gourmand', 'Notes de iris et praline pour une féminité douce et enveloppante.', 115.00, null, '#', '#', 'Sephora', 0.06, null, null, null, ARRAY['romantique','douce'], ARRAY['quotidien','soirée'], ARRAY['25-35','35-45'], 88, 82, 73, 85, 60, 'in_stock'),
  ('Parfum niche oud - Baccarat Rouge 540', 'Maison Francis Kurkdjian', 'perfume', 'woody', 'Fragrance luxueuse aux facettes ambrées et florales, la signature des connaisseurs.', 340.00, null, '#', '#', 'MFK', 0.04, null, null, null, ARRAY['luxe','sophistiquée'], ARRAY['soirée','occasions spéciales'], ARRAY['25-35','35-45','45+'], 98, 88, 60, 95, 40, 'in_stock'),
  ('EDT fraîche fruitée - Chance Fraîche', 'Chanel', 'perfume', 'fresh', 'Interprétation fraîche et fruitée du Chance original, légèreté printanière.', 140.00, null, '#', '#', 'Chanel', 0.04, null, null, null, ARRAY['romantique','fraîche'], ARRAY['quotidien','bureau'], ARRAY['18-25','25-35'], 92, 85, 68, 88, 40, 'in_stock'),
  ('Parfum boisé rose - Mon Guerlain', 'Guerlain', 'perfume', 'floral', 'Fragrance féminine inspirée de la Provence, lavande et vanille bourbon.', 108.00, null, '#', '#', 'Sephora', 0.06, null, null, null, ARRAY['romantique','naturelle'], ARRAY['quotidien','soirée'], ARRAY['25-35','35-45'], 88, 84, 74, 83, 60, 'in_stock'),
  ('Eau de parfum aquatique', 'Issey Miyake', 'perfume', 'aquatic', 'L''Eau d''Issey : mélopée aquatique fraîche et minérale, légèreté absolue.', 95.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['minimaliste','fraîche'], ARRAY['quotidien','bureau'], ARRAY['25-35','35-45','45+'], 88, 83, 78, 80, 70, 'in_stock'),

  -- ACCESSORIES
  ('Sac cabas en cuir vachette', 'Polène', 'style', 'accessories', 'Sac cabas structuré en cuir pleine fleur, poignées et bandoulière amovible.', 265.00, null, '#', '#', 'Polène', 0.06, 'Cuir vachette', null, ARRAY['camel','noir','écru','terracotta'], ARRAY['chic','minimaliste'], ARRAY['bureau','quotidien'], ARRAY['25-35','35-45'], 92, 85, 78, 90, 60, 'in_stock'),
  ('Lunettes de soleil cat-eye', 'Le Specs', 'style', 'accessories', 'Monture cat-eye acétate légère, verres polarisés UV400, look rétro.', 69.00, null, '#', '#', 'Le Specs', 0.07, 'Acétate', ARRAY['unique'], ARRAY['noir','écaille','blanc'], ARRAY['rétro','chic','tendance'], ARRAY['quotidien','plage'], ARRAY['18-25','25-35','35-45'], 85, 88, 82, 88, 70, 'in_stock'),
  ('Ceinture en cuir dorée', 'Maje', 'style', 'accessories', 'Ceinture fine en cuir nappa avec boucle dorée brillante, élégance ultime.', 95.00, null, '#', '#', 'Maje', 0.07, 'Cuir nappa', ARRAY['S','M','L'], ARRAY['noir','marron','blanc'], ARRAY['chic','classique'], ARRAY['bureau','soirée'], ARRAY['25-35','35-45'], 85, 82, 78, 85, 70, 'in_stock'),
  ('Chapeau de paille tressée', 'Lack of Color', 'style', 'accessories', 'Chapeau de paille à large bord, doublure en coton, ruban natural noué.', 120.00, null, '#', '#', 'Lack of Color', 0.07, 'Paille naturelle', ARRAY['S/M','M/L'], ARRAY['naturel','blanc'], ARRAY['bohème','vacances'], ARRAY['plage','week-end'], ARRAY['18-25','25-35','35-45'], 88, 85, 75, 88, 70, 'in_stock'),
  ('Boucles d''oreilles créoles', 'Gorjana', 'style', 'accessories', 'Créoles en argent plaqué or 18 carats, diamètre 40mm, légères et polyvalentes.', 68.00, null, '#', '#', 'Gorjana', 0.08, 'Argent/or 18k', ARRAY['unique'], ARRAY['or','argent'], ARRAY['chic','casual'], ARRAY['quotidien','bureau','soirée'], ARRAY['18-25','25-35','35-45'], 85, 88, 80, 88, 80, 'in_stock'),
  ('Foulard en soie imprimé', 'Hermès', 'style', 'accessories', 'Carré de soie 90x90 imprimé motifs chevaux, pièce iconique de la maison.', 395.00, null, '#', '#', 'Hermès', 0.04, 'Soie', ARRAY['90x90'], ARRAY['multicolore'], ARRAY['luxe','chic','classique'], ARRAY['bureau','soirée'], ARRAY['25-35','35-45','45+'], 98, 92, 62, 88, 40, 'in_stock'),
  ('Sac banane en nylon', 'Longchamp', 'style', 'accessories', 'Sac banane léger en nylon résistant, pratique pour les journées actives.', 95.00, null, '#', '#', 'Longchamp', 0.06, 'Nylon', ARRAY['unique'], ARRAY['noir','rouge','marine'], ARRAY['casual','sport','tendance'], ARRAY['quotidien','week-end'], ARRAY['18-25','25-35'], 85, 82, 80, 82, 60, 'in_stock'),

  -- GIFTS
  ('Bougie parfumée en cire de soja', 'Diptyque', 'gifts', 'home', 'Bougie Baies emblématique en cire de soja, 70h de diffusion, coffret cadeau.', 47.00, null, '#', '#', 'Diptyque', 0.06, null, null, null, ARRAY['romantique','minimaliste'], ARRAY['maison'], ARRAY['18-25','25-35','35-45','45+'], 95, 88, 72, 90, 60, 'in_stock'),
  ('Coffret soins du corps luxe', 'Jo Malone', 'gifts', 'beauty', 'Coffret comprenant gel douche, lait corps et eau de cologne, parfum Peony & Blush.', 89.00, null, '#', '#', 'Jo Malone', 0.06, null, null, null, ARRAY['luxe','romantique'], ARRAY['cadeau'], ARRAY['25-35','35-45','45+'], 92, 88, 70, 88, 60, 'in_stock'),
  ('Coffret maquillage mini', 'Charlotte Tilbury', 'gifts', 'beauty', 'Mini coffret Stars in your eyes : mascara, gloss, highlighter et blush.', 52.00, null, '#', '#', 'Charlotte Tilbury', 0.07, null, null, null, ARRAY['maquillage'], ARRAY['cadeau'], ARRAY['18-25','25-35','35-45'], 90, 84, 74, 88, 70, 'in_stock'),
  ('Carnet en cuir gravé', 'Papier Tigre', 'gifts', 'accessories', 'Carnet A5 en cuir recyclé avec papier ivoire certifié, options de gravure personnalisée.', 38.00, null, '#', '#', 'Papier Tigre', 0.07, 'Cuir recyclé', null, ARRAY['noir','cognac','forêt'], ARRAY['minimaliste','élégante'], ARRAY['cadeau'], ARRAY['18-25','25-35','35-45'], 88, 85, 80, 80, 70, 'in_stock'),
  ('Plaid en laine mérinos', 'Zara Home', 'gifts', 'home', 'Plaid ultra-doux en laine mérinos fine, coloris naturels, format 130x180cm.', 79.00, null, '#', '#', 'Zara Home', 0.07, 'Laine mérinos', null, ARRAY['écru','gris perle','camel'], ARRAY['romantique','cosy'], ARRAY['maison'], ARRAY['18-25','25-35','35-45','45+'], 90, 88, 80, 85, 70, 'in_stock'),
  ('Kit rituel spa maison', 'Caudalie', 'gifts', 'beauty', 'Kit 5 produits Vinothérapie pour un rituel spa luxueux à la maison.', 65.00, null, '#', '#', 'Caudalie', 0.07, null, null, null, ARRAY['naturel','luxe'], ARRAY['cadeau'], ARRAY['25-35','35-45','45+'], 90, 90, 74, 85, 70, 'in_stock'),
  ('Bijou personnalisé prénom', 'Miloo', 'gifts', 'jewelry', 'Bracelet fin en or 18k avec prénom gravé, personnalisation gratuite.', 89.00, null, '#', '#', 'Miloo', 0.08, 'Or 18k', null, ARRAY['or'], ARRAY['romantique','classique'], ARRAY['cadeau','quotidien'], ARRAY['18-25','25-35','35-45'], 88, 90, 78, 88, 80, 'in_stock'),
  ('Livre table basse mode', 'Assouline', 'gifts', 'books', 'Livre d''art Chanel : une histoire du luxe français, livre collector.', 95.00, null, '#', '#', 'Assouline', 0.05, null, null, null, ARRAY['luxe','classique'], ARRAY['cadeau'], ARRAY['25-35','35-45','45+'], 95, 90, 72, 88, 50, 'in_stock'),
  ('Subscription box beauté', 'Birchbox', 'gifts', 'subscription', 'Box beauté mensuelle 5 produits taille voyage sélectionnés pour ton profil.', 14.99, null, '#', '#', 'Birchbox', 0.09, null, null, null, ARRAY['soin','maquillage'], ARRAY['cadeau'], ARRAY['18-25','25-35','35-45'], 80, 82, 88, 82, 90, 'in_stock'),

  -- SHOES
  ('Bottines chelsea en cuir', 'Vagabond', 'style', 'shoes', 'Chelsea boots en cuir pleine fleur, semelle crêpe légère, faciles à enfiler.', 175.00, null, '#', '#', 'Vagabond', 0.07, 'Cuir', ARRAY['36','37','38','39','40','41'], ARRAY['noir','cognac','blanc'], ARRAY['casual','chic','minimaliste'], ARRAY['quotidien','bureau'], ARRAY['18-25','25-35','35-45'], 90, 85, 80, 88, 70, 'in_stock'),
  ('Mules à talons sculptés', 'Jacquemus', 'style', 'shoes', 'Mules à talon sculpté en résine transparente, semelle cuir gravée.', 290.00, null, '#', '#', 'Jacquemus', 0.05, 'Cuir/résine', ARRAY['36','37','38','39','40'], ARRAY['nude','blanc','noir'], ARRAY['tendance','chic','luxe'], ARRAY['soirée','bureau'], ARRAY['25-35'], 88, 80, 70, 95, 50, 'in_stock'),
  ('Sneakers cuir minimaliste', 'Veja', 'style', 'shoes', 'Sneakers V-10 en cuir B-Mesh biologique, production éco-responsable.', 150.00, null, '#', '#', 'Veja', 0.06, 'Cuir B-Mesh', ARRAY['36','37','38','39','40','41'], ARRAY['blanc/rouge','blanc/vert','noir'], ARRAY['casual','minimaliste','tendance'], ARRAY['quotidien','week-end'], ARRAY['18-25','25-35','35-45'], 92, 92, 82, 90, 60, 'in_stock'),
  ('Escarpins en daim à talon', 'Sam Edelman', 'style', 'shoes', 'Escarpins en daim talonné 8cm, bout carré tendance, intérieur confort.', 98.00, null, '#', '#', 'Sam Edelman', 0.07, 'Daim synthétique', ARRAY['36','37','38','39','40'], ARRAY['nude','noir','bordeaux'], ARRAY['chic','classique'], ARRAY['bureau','soirée'], ARRAY['25-35','35-45'], 83, 78, 80, 82, 70, 'in_stock'),
  ('Sandales plates tressées', 'Ancient Greek Sandals', 'style', 'shoes', 'Sandales en cuir tressé fait main à Athènes, style mykonos intemporel.', 195.00, null, '#', '#', 'AGS', 0.06, 'Cuir naturel', ARRAY['36','37','38','39','40','41'], ARRAY['naturel','blanc','noir'], ARRAY['bohème','chic','vacances'], ARRAY['plage','week-end'], ARRAY['18-25','25-35','35-45'], 90, 88, 74, 88, 60, 'in_stock'),

  -- HOME LIFESTYLE
  ('Diffuseur à ultrasons', 'Muji', 'gifts', 'home', 'Diffuseur ultrasonique silencieux en céramique blanche, 200ml.', 45.00, null, '#', '#', 'Muji', 0.06, null, null, null, ARRAY['minimaliste'], ARRAY['maison'], ARRAY['18-25','25-35','35-45','45+'], 88, 85, 82, 82, 60, 'in_stock'),
  ('Carafe en verre borosilicate', 'Maison Balzac', 'gifts', 'home', 'Carafe en verre soufflé bouche avec bouchon liège naturel, 1L.', 65.00, null, '#', '#', 'Maison Balzac', 0.07, 'Verre borosilicate', null, null, ARRAY['minimaliste','chic'], ARRAY['maison'], ARRAY['18-25','25-35','35-45'], 90, 92, 80, 85, 70, 'in_stock'),
  ('Coussin brodé en velours', 'Zara Home', 'gifts', 'home', 'Coussin 50x50cm en velours avec broderie florale, garnissage inclus.', 49.90, null, '#', '#', 'Zara Home', 0.07, 'Velours polyester', null, ARRAY['rose poudré','vert sauge','écru'], ARRAY['romantique','bohème'], ARRAY['maison'], ARRAY['18-25','25-35','35-45'], 83, 80, 80, 82, 70, 'in_stock'),
  ('Tapis de yoga anti-dérapant', 'Manduka', 'style', 'accessories', 'Tapis PRO 6mm en caoutchouc naturel recyclé, grip exceptionnel et longévité.', 140.00, null, '#', '#', 'Manduka', 0.06, 'Caoutchouc naturel', null, ARRAY['noir','violet','forêt'], ARRAY['sport','minimaliste'], ARRAY['sport'], ARRAY['18-25','25-35','35-45'], 95, 90, 78, 85, 60, 'in_stock'),

  -- LINGERIE
  ('Bralette dentelle fine', 'Intimissimi', 'style', 'lingerie', 'Bralette non-filtrante en dentelle florentine, très élégante et confortable.', 39.90, null, '#', '#', 'Intimissimi', 0.07, 'Dentelle polyamide', ARRAY['XS','S','M','L'], ARRAY['ivoire','noir','rose poudré'], ARRAY['romantique','chic'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45'], 88, 80, 80, 85, 70, 'in_stock'),
  ('Ensemble pyjama en soie', 'Morgan Lane', 'style', 'lingerie', 'Ensemble pyjama chemise et short en satin de soie, motif géométrique imprimé.', 285.00, null, '#', '#', 'Morgan Lane', 0.06, 'Soie', ARRAY['XS','S','M','L'], ARRAY['rose champagne','bleu nuit'], ARRAY['luxe','romantique'], ARRAY['maison'], ARRAY['25-35','35-45'], 92, 88, 68, 88, 60, 'in_stock'),
  ('Culotte taille haute en coton', 'Baserange', 'style', 'lingerie', 'Culotte taille haute en coton biologique doux, silhouette naturelle.', 45.00, null, '#', '#', 'Baserange', 0.07, 'Coton bio', ARRAY['XS','S','M','L','XL'], ARRAY['blanc','noir','terracotta'], ARRAY['minimaliste','naturel'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45'], 88, 93, 82, 80, 70, 'in_stock'),

  -- FITNESS/WELLNESS
  ('Bouteille isotherme en acier', 'Swell', 'gifts', 'wellness', 'Bouteille inox double paroi 750ml, maintien chaud 12h/froid 24h, sans BPA.', 45.00, null, '#', '#', 'S''well', 0.07, 'Acier inox', ARRAY['750ml'], ARRAY['rose gold','marbre','navy'], ARRAY['sport','minimaliste'], ARRAY['sport','quotidien'], ARRAY['18-25','25-35','35-45'], 90, 95, 82, 82, 70, 'in_stock'),
  ('Bande de résistance set 5', 'Gymreapers', 'style', 'accessories', 'Set 5 bandes de résistance latex premium, étui de rangement inclus.', 29.99, null, '#', '#', 'Gymreapers', 0.09, 'Latex naturel', null, ARRAY['multicolore'], ARRAY['sport','athleisure'], ARRAY['sport'], ARRAY['18-25','25-35','35-45'], 85, 85, 90, 80, 90, 'in_stock'),

  -- MORE STYLE
  ('Robe de mariée boho', 'Grace Loves Lace', 'style', 'dresses', 'Robe de mariée en dentelle Stretch de Venise, allure bohème romantique.', 2200.00, null, '#', '#', 'Grace Loves Lace', 0.04, 'Dentelle de Venise', ARRAY['XS','S','M','L','XL'], ARRAY['ivoire'], ARRAY['romantique','bohème','luxe'], ARRAY['mariage'], ARRAY['25-35','35-45'], 98, 90, 55, 90, 40, 'in_stock'),
  ('Jumpsuit lin écru', 'Toteme', 'style', 'dresses', 'Jumpsuit taille haute en lin brossé, jambes larges, ceinture incluse.', 360.00, null, '#', '#', 'Toteme', 0.05, 'Lin', ARRAY['XS','S','M','L'], ARRAY['écru','noir'], ARRAY['minimaliste','chic'], ARRAY['bureau','soirée'], ARRAY['25-35','35-45'], 92, 85, 70, 90, 50, 'in_stock'),
  ('Mini jupe cargo kaki', 'Diesel', 'style', 'bottoms', 'Mini jupe cargo en denim kaki avec poches latérales, style edgy-casual.', 130.00, null, '#', '#', 'Diesel', 0.06, 'Denim coton', ARRAY['XS','S','M','L'], ARRAY['kaki','noir'], ARRAY['rock','tendance','casual'], ARRAY['week-end','soirée'], ARRAY['18-25'], 82, 78, 78, 92, 60, 'in_stock'),
  ('Veste matelassée sans manches', 'Barbour', 'style', 'outerwear', 'Veste gilet matelassé en nylon, emblème du style anglais chic.', 179.00, null, '#', '#', 'Barbour', 0.05, 'Nylon/coton', ARRAY['XS','S','M','L','XL'], ARRAY['marine','kaki','rouge'], ARRAY['classique','chic','outdoor'], ARRAY['week-end','quotidien'], ARRAY['25-35','35-45'], 88, 85, 80, 82, 50, 'in_stock'),
  ('Robe longue imprimé léopard', 'Never Fully Dressed', 'style', 'dresses', 'Maxi robe portefeuille en viscose imprimé léopard, féminine et fluide.', 95.00, null, '#', '#', 'Never Fully Dressed', 0.07, 'Viscose', ARRAY['XS','S','M','L','XL'], ARRAY['léopard'], ARRAY['tendance','bohème','festif'], ARRAY['soirée','week-end'], ARRAY['18-25','25-35'], 82, 78, 80, 92, 70, 'in_stock'),
  ('Body à dentelle noire', 'Alix NYC', 'style', 'lingerie', 'Body stretch en dentelle fine noir, bretelles réglables, fermeture dos.', 185.00, null, '#', '#', 'Alix NYC', 0.06, 'Nylon/dentelle', ARRAY['XS','S','M','L'], ARRAY['noir'], ARRAY['séductrice','chic'], ARRAY['soirée','bureau'], ARRAY['18-25','25-35'], 88, 80, 74, 90, 60, 'in_stock'),
  ('Sac à main quilted chain', 'Maje', 'style', 'accessories', 'Sac matelassé chaîne dorée style parisien, taille mini-pochette.', 165.00, null, '#', '#', 'Maje', 0.07, 'Cuir synthétique', ARRAY['unique'], ARRAY['noir','bordeaux','beige'], ARRAY['chic','tendance'], ARRAY['soirée','bureau'], ARRAY['18-25','25-35','35-45'], 82, 78, 78, 90, 70, 'in_stock'),
  ('Boots western à bout pointu', 'Isabel Marant', 'style', 'shoes', 'Boots western en cuir nubuck avec détails brodés, talon empilé 5cm.', 690.00, null, '#', '#', 'Isabel Marant', 0.05, 'Cuir nubuck', ARRAY['36','37','38','39','40'], ARRAY['noir','cognac','kaki'], ARRAY['bohème','chic','rock'], ARRAY['quotidien','soirée'], ARRAY['25-35','35-45'], 93, 85, 68, 92, 50, 'in_stock'),
  ('Pantalon large en cuir vegan', 'Stand Studio', 'style', 'bottoms', 'Pantalon large en faux cuir, style 70s glam avec ceinture à nouer.', 325.00, null, '#', '#', 'Stand Studio', 0.05, 'Polyuréthane', ARRAY['XS','S','M','L'], ARRAY['noir','camel'], ARRAY['tendance','chic','luxe'], ARRAY['soirée'], ARRAY['25-35'], 85, 75, 72, 93, 50, 'in_stock'),
  ('Crop hoodie brodé', 'Sporty & Rich', 'style', 'tops', 'Crop hoodie en molleton coton épais, logo brodé retro, coupe boxy.', 175.00, null, '#', '#', 'Sporty & Rich', 0.06, 'Coton', ARRAY['XS','S','M','L'], ARRAY['crème/bleu','rose/blanc','blanc/vert'], ARRAY['athleisure','tendance','casual'], ARRAY['quotidien','sport'], ARRAY['18-25','25-35'], 88, 85, 76, 92, 60, 'in_stock'),
  ('Robe de chambre en cachemire', 'Morphée Paris', 'gifts', 'home', 'Peignoir en cachemire et laine mérinos, ceinture et poches, ultra-doux.', 480.00, null, '#', '#', 'Morphée', 0.05, 'Cachemire/mérinos', ARRAY['S/M','M/L','L/XL'], ARRAY['ivoire','gris perle'], ARRAY['luxe','cosy'], ARRAY['maison'], ARRAY['25-35','35-45','45+'], 96, 92, 62, 85, 50, 'in_stock'),

  -- More beauty
  ('Palette visage glow', 'Hourglass', 'beauty', 'makeup', 'Palette Ambient Lighting avec 3 finishers poudre translucide pour un teint lumineux.', 65.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['maquillage'], ARRAY['bureau','soirée'], ARRAY['18-25','25-35','35-45'], 92, 84, 75, 90, 70, 'in_stock'),
  ('Fond de teint teinte adaptative', 'Lancôme', 'beauty', 'makeup', 'Teint Idole Ultra Wear en 50 teintes, tenue 24h, résistant à l''humidité.', 42.00, null, '#', '#', 'Sephora', 0.07, null, null, null, ARRAY['maquillage'], ARRAY['bureau','quotidien'], ARRAY['25-35','35-45'], 90, 83, 78, 83, 70, 'in_stock'),
  ('Gloss à plumping effect', 'Dior', 'beauty', 'makeup', 'Lip Maximizer repulpant avec acide hyaluronique, 25 nuances scintillantes.', 36.00, null, '#', '#', 'Sephora', 0.06, null, null, null, ARRAY['maquillage'], ARRAY['quotidien','soirée'], ARRAY['18-25','25-35'], 88, 82, 78, 90, 60, 'in_stock'),
  ('Eye-liner pinceau ultra-précis', 'Stila', 'beauty', 'makeup', 'Eye-liner Stay All Day longue tenue, imperméable, applicateur pinceau.', 26.00, null, '#', '#', 'Sephora', 0.08, null, null, null, ARRAY['maquillage'], ARRAY['bureau','soirée'], ARRAY['18-25','25-35','35-45'], 90, 82, 82, 85, 80, 'in_stock'),
  ('Sérum retinol nuit', 'Paula''s Choice', 'beauty', 'skincare', 'Sérum 1% Retinol avec antioxydants, améliore rides et texture, nuit.', 60.00, null, '#', '#', 'Paula''s Choice', 0.07, null, null, null, ARRAY['soin'], ARRAY['quotidien'], ARRAY['35-45','45+'], 92, 87, 78, 85, 70, 'in_stock'),
  ('Crème anti-cellulite caffeine', 'Sol de Janeiro', 'beauty', 'bodycare', 'Crème brésilienne à la caféine et guarana pour peau lissée et tonifiée.', 38.00, null, '#', '#', 'Sephora', 0.08, null, null, null, ARRAY['soin'], ARRAY['quotidien'], ARRAY['18-25','25-35','35-45'], 83, 82, 80, 85, 80, 'in_stock');
